export class Quote
{
 language                               :String
 region                                 :String
 quoteType                              :String
 typeDisp                               :String
 quoteSourceName                        :String
 triggerable                            :String
 customPriceAlertConfidence             :String
 currency                               :String
 regularMarketChangePercent             :String
 regularMarketPrice                     :String
 marketState                            :String
 exchange                               :String
 shortName                              :String
 longName                               :String
 messageBoardId                         :String
 exchangeTimezoneName                   :String
 exchangeTimezoneShortName              :String
 gmtOffSetMilliseconds                  :String
 market                                 :String
 esgPopulated                           :String
 tradeable                              :String
 cryptoTradeable                        :String
 regularMarketChange                    :String
 regularMarketTime                      :String
 regularMarketDayHigh                   :String
 regularMarketDayRange                  :String
 regularMarketDayLow                    :String
 regularMarketVolume                    :String
 regularMarketPreviousClose             :String
 bid                                    :String
 ask                                    :String
 bidSize                                :String
 askSize                                :String
 fullExchangeName                       :String
 financialCurrency                      :String
 regularMarketOpen                      :String
 averageDailyVolume3Month               :String
 averageDailyVolume10Day                :String
 fiftyTwoWeekLowChange                  :String
 fiftyTwoWeekLowChangePercent           :String
 fiftyTwoWeekRange                      :String
 fiftyTwoWeekHighChange                 :String
 fiftyTwoWeekHighChangePercent          :String
 fiftyTwoWeekLow                        :String
 fiftyTwoWeekHigh                       :String
 dividendDate                           :String
 earningsTimestamp                      :String
 earningsTimestampStart                 :String
 earningsTimestampEnd                   :String
 trailingAnnualDividendRate             :String
 trailingPE                             :String
 trailingAnnualDividendYield            :String
 epsTrailingTwelveMonths                :String
 epsForward                             :String
 epsCurrentYear                         :String
 priceEpsCurrentYear                    :String
 sharesOutstanding                      :String
 bookValue                              :String
 fiftyDayAverage                        :String
 fiftyDayAverageChange                  :String
 fiftyDayAverageChangePercent           :String
 twoHundredDayAverage                   :String
 twoHundredDayAverageChange             :String
 twoHundredDayAverageChangePercent      :String
 marketCap                              :String
 forwardPE                              :String
 priceToBook                            :String
 sourceInterval                         :String
 exchangeDataDelayedBy                  :String
 averageAnalystRating                   :String
 firstTradeDateMilliseconds             :String
 priceHint                              :String
 preMarketChange                        :String
 preMarketChangePercent                 :String
 preMarketTime                          :String
 preMarketPrice                         :String
 displayName                            :String
 symbol									:String
}